### ISSUE TITLE
Command streaming

### ISSUE THREAD

**Issue by mbajur** [myobie/fancy_command#1]
Hello there,

i'm trying to use fancy_command gem as a part of my personal "unix commands streaming through ruby" research but am not able to use it as desired.

What i want to do is to stream/display/whatever each line of long-running unix commands triggered by ruby. Like `$ ping` for example. If i understand it all well, the follwing snipped should display each ping attempt line by line:

    run('ping -c 10 github.com', accum: $stdout)

but really all i can see is 10 seconds lag and a whole output displayed when ping finishes. Which is totally not what i'm aming for.

Have you any idea on what i'm doing/getting wrong? Thanks in advance!

**Comment by myobie** [comment]
@mbajur When I run your command I see the ping output come in each line at a time.

I'd like to try to help you diagnose why the output might have queued up. Do you mind to answer a few questions:

1. What version of ruby are you using? (I tested with 2.3.3)
2. Can you run the same command with `verbose: true` and paste the entire output?
3. Have you modified `$stdout` before running `run`?
4. To make sure nothing else is affecting it, maybe run `$ ruby -r fancy_command -e 'include FancyCommand; run("ping -c 10 github.com", accum: $stdout)'`?

Let me know and I'll try to help you.

- - -

I also recommend you try using Open3.popen3 if you are learning about unix pipes and ruby: https://github.com/myobie/fancy_command/blob/master/lib/fancy_command/command.rb#L58-L89

The docs are here: http://ruby-doc.org/stdlib-2.3.3/libdoc/open3/rdoc/Open3.html#method-c-popen3

I had fun learning about all of that when I made this library.

**Comment by mbajur** [comment]
Actually Open3 was the thing i've tried before fancy_command :) And continued my research cause Open3 was behaving the same way.

1. I'm on ruby 2.3.0p0
2. It behaves the same way, just the command is getting displayed: https://gist.github.com/mbajur/4bd7cd59eab4d6feb5987a1b23cdf656
3. Nope
4. I'm not sure how to run it cause i need to use bundle exec for this i suppose. Anyway, it throws that fancy_command not found but i'm pretty sure it's more related to my setup (docker, docker-dind) rather than any issue

One thing that comes to my mind is that i'm running that code/app inside a docker container (actually docker in a docker). Is there any change that OS needs to have some libs installed to make such feature available?

Thanks for your super fast reply! :)

**Comment by myobie** [comment]
@mbajur ok, I think you have revealed some new information that will help us.

The first thing I noticed that really implicates something outside ruby is this:

```
<page break> --- Press enter to continue ( q<enter> to break ) --- <page break>
```

That seems like everything is being piped through less or some other buffering type thing. This is the first thing I would look into, because it really seems like it is what is buffering your output.

Second, you are using `pry` and not just `irb`. So I tested `pry` and I still get the ping output line by line, so I think we can assume `pry` is working fine.

Third, you are using `docker`. I don't have `docker` handy at the moment, but depending on how you enter the container could mean your `stdout` is affected. Are you able to install ruby on your host machine for testing? Or does your workflow depend 100% on `docker`?

Can you post the full list of commands that leads up to you running the `FancyCommand` related ruby code?

**Comment by myobie** [comment]
Oh, and I made this gist that you could clone and try out inside your docker container if you want that is very isolated: https://gist.github.com/myobie/22451d0c7f308516ef8efc7a2e8b2704
